name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest-arm64
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5

    - name: Read version from debian/changelog
      id: version
      run: |
        VERSION=$(dpkg-parsechangelog -S Version)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"

    - name: Build packages
      run: |
        ./run package:deb:docker:ci

    - name: Collect built packages
      run: |
        mkdir -p packages
        find . .. -maxdepth 1 -name "*.deb" -exec cp {} packages/ \; 2>/dev/null || true
        ls -la packages/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: packages/*.deb
        body: |
          ## Runtipi Docker Service v${{ steps.version.outputs.version }}

          Debian package for Runtipi containerized service.

          ### Installation

          ```bash
          wget https://github.com/hatlabs/runtipi-docker-service/releases/download/${{ github.ref_name }}/runtipi-docker-service_${{ steps.version.outputs.version }}_all.deb
          sudo dpkg -i runtipi-docker-service_${{ steps.version.outputs.version }}_all.deb
          ```

          ### What's Included

          - Runtipi CLI $(cat VERSION)
          - Systemd service for automatic startup
          - Installation to /opt/runtipi

          See README.md for usage instructions.
        draft: false
        prerelease: false
