name: Release Published

on:
  release:
    types: [published]

jobs:
  notify-apt-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Extract version from tag
      id: version
      run: |
        # Extract version from tag (remove 'v' prefix if present)
        VERSION="${{ github.event.release.tag_name }}"
        VERSION="${VERSION#v}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"

    - name: Trigger APT repository update
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.APT_REPO_PAT }}
        repository: hatlabs/apt.hatlabs.fi
        event-type: package-updated
        client-payload: |
          {
            "package": "${{ github.event.repository.name }}",
            "version": "${{ steps.version.outputs.version }}",
            "repository": "${{ github.repository }}"
          }
